# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import migration_pb2 as migration__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in migration_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MigrationServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListNodes = channel.unary_unary(
                '/migration.MigrationService/ListNodes',
                request_serializer=migration__pb2.Empty.SerializeToString,
                response_deserializer=migration__pb2.NodeListResponse.FromString,
                _registered_method=True)
        self.MigrateContainer = channel.unary_unary(
                '/migration.MigrationService/MigrateContainer',
                request_serializer=migration__pb2.MigrateRequest.SerializeToString,
                response_deserializer=migration__pb2.MigrateResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/migration.MigrationService/GetJobStatus',
                request_serializer=migration__pb2.JobStatusRequest.SerializeToString,
                response_deserializer=migration__pb2.JobStatusResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/migration.MigrationService/ListJobs',
                request_serializer=migration__pb2.Empty.SerializeToString,
                response_deserializer=migration__pb2.JobListResponse.FromString,
                _registered_method=True)
        self.Refresh = channel.unary_unary(
                '/migration.MigrationService/Refresh',
                request_serializer=migration__pb2.Empty.SerializeToString,
                response_deserializer=migration__pb2.Empty.FromString,
                _registered_method=True)
        self.StartContainer = channel.unary_unary(
                '/migration.MigrationService/StartContainer',
                request_serializer=migration__pb2.StartContainerRequest.SerializeToString,
                response_deserializer=migration__pb2.StartContainerResponse.FromString,
                _registered_method=True)
        self.AddNode = channel.unary_unary(
                '/migration.MigrationService/AddNode',
                request_serializer=migration__pb2.AddNodeRequest.SerializeToString,
                response_deserializer=migration__pb2.AddNodeResponse.FromString,
                _registered_method=True)
        self.RemoveNode = channel.unary_unary(
                '/migration.MigrationService/RemoveNode',
                request_serializer=migration__pb2.RemoveNodeRequest.SerializeToString,
                response_deserializer=migration__pb2.RemoveNodeResponse.FromString,
                _registered_method=True)
        self.SetNodes = channel.unary_unary(
                '/migration.MigrationService/SetNodes',
                request_serializer=migration__pb2.SetNodesRequest.SerializeToString,
                response_deserializer=migration__pb2.SetNodesResponse.FromString,
                _registered_method=True)
        self.StartInteractiveMigrate = channel.unary_unary(
                '/migration.MigrationService/StartInteractiveMigrate',
                request_serializer=migration__pb2.StartInteractiveMigrateRequest.SerializeToString,
                response_deserializer=migration__pb2.StartInteractiveMigrateResponse.FromString,
                _registered_method=True)
        self.PreDumpInteractive = channel.unary_unary(
                '/migration.MigrationService/PreDumpInteractive',
                request_serializer=migration__pb2.PreDumpInteractiveRequest.SerializeToString,
                response_deserializer=migration__pb2.PreDumpInteractiveResponse.FromString,
                _registered_method=True)
        self.FinalInteractiveMigrate = channel.unary_unary(
                '/migration.MigrationService/FinalInteractiveMigrate',
                request_serializer=migration__pb2.FinalInteractiveMigrateRequest.SerializeToString,
                response_deserializer=migration__pb2.FinalInteractiveMigrateResponse.FromString,
                _registered_method=True)


class MigrationServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MigrateContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Refresh(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartContainer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartInteractiveMigrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreDumpInteractive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FinalInteractiveMigrate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MigrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=migration__pb2.Empty.FromString,
                    response_serializer=migration__pb2.NodeListResponse.SerializeToString,
            ),
            'MigrateContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.MigrateContainer,
                    request_deserializer=migration__pb2.MigrateRequest.FromString,
                    response_serializer=migration__pb2.MigrateResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=migration__pb2.JobStatusRequest.FromString,
                    response_serializer=migration__pb2.JobStatusResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=migration__pb2.Empty.FromString,
                    response_serializer=migration__pb2.JobListResponse.SerializeToString,
            ),
            'Refresh': grpc.unary_unary_rpc_method_handler(
                    servicer.Refresh,
                    request_deserializer=migration__pb2.Empty.FromString,
                    response_serializer=migration__pb2.Empty.SerializeToString,
            ),
            'StartContainer': grpc.unary_unary_rpc_method_handler(
                    servicer.StartContainer,
                    request_deserializer=migration__pb2.StartContainerRequest.FromString,
                    response_serializer=migration__pb2.StartContainerResponse.SerializeToString,
            ),
            'AddNode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNode,
                    request_deserializer=migration__pb2.AddNodeRequest.FromString,
                    response_serializer=migration__pb2.AddNodeResponse.SerializeToString,
            ),
            'RemoveNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNode,
                    request_deserializer=migration__pb2.RemoveNodeRequest.FromString,
                    response_serializer=migration__pb2.RemoveNodeResponse.SerializeToString,
            ),
            'SetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNodes,
                    request_deserializer=migration__pb2.SetNodesRequest.FromString,
                    response_serializer=migration__pb2.SetNodesResponse.SerializeToString,
            ),
            'StartInteractiveMigrate': grpc.unary_unary_rpc_method_handler(
                    servicer.StartInteractiveMigrate,
                    request_deserializer=migration__pb2.StartInteractiveMigrateRequest.FromString,
                    response_serializer=migration__pb2.StartInteractiveMigrateResponse.SerializeToString,
            ),
            'PreDumpInteractive': grpc.unary_unary_rpc_method_handler(
                    servicer.PreDumpInteractive,
                    request_deserializer=migration__pb2.PreDumpInteractiveRequest.FromString,
                    response_serializer=migration__pb2.PreDumpInteractiveResponse.SerializeToString,
            ),
            'FinalInteractiveMigrate': grpc.unary_unary_rpc_method_handler(
                    servicer.FinalInteractiveMigrate,
                    request_deserializer=migration__pb2.FinalInteractiveMigrateRequest.FromString,
                    response_serializer=migration__pb2.FinalInteractiveMigrateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'migration.MigrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('migration.MigrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MigrationService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/ListNodes',
            migration__pb2.Empty.SerializeToString,
            migration__pb2.NodeListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MigrateContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/MigrateContainer',
            migration__pb2.MigrateRequest.SerializeToString,
            migration__pb2.MigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/GetJobStatus',
            migration__pb2.JobStatusRequest.SerializeToString,
            migration__pb2.JobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/ListJobs',
            migration__pb2.Empty.SerializeToString,
            migration__pb2.JobListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Refresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/Refresh',
            migration__pb2.Empty.SerializeToString,
            migration__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartContainer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/StartContainer',
            migration__pb2.StartContainerRequest.SerializeToString,
            migration__pb2.StartContainerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/AddNode',
            migration__pb2.AddNodeRequest.SerializeToString,
            migration__pb2.AddNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/RemoveNode',
            migration__pb2.RemoveNodeRequest.SerializeToString,
            migration__pb2.RemoveNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/SetNodes',
            migration__pb2.SetNodesRequest.SerializeToString,
            migration__pb2.SetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartInteractiveMigrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/StartInteractiveMigrate',
            migration__pb2.StartInteractiveMigrateRequest.SerializeToString,
            migration__pb2.StartInteractiveMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreDumpInteractive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/PreDumpInteractive',
            migration__pb2.PreDumpInteractiveRequest.SerializeToString,
            migration__pb2.PreDumpInteractiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FinalInteractiveMigrate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/migration.MigrationService/FinalInteractiveMigrate',
            migration__pb2.FinalInteractiveMigrateRequest.SerializeToString,
            migration__pb2.FinalInteractiveMigrateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
